### ISSUE TITLE
Need to commit ./bin/www

### ISSUE THREAD

**Issue by jeremiahbuckley** [jwilliams33490/save-a-little-service#1]
It looks like this is local to your machine, but not checked in to github.

**Comment by jwilliams33490** [comment]
fixed by https://github.com/jwilliams33490/save-a-little-service/commit/b3101e6a692e223e99c251b5bed323339d78909d

**Comment by jwilliams33490** [comment]
fixed by https://github.com/jwilliams33490/save-a-little-service/commit/b3101e6a692e223e99c251b5bed323339d78909d
